export const SET_NOTE = "SET_NOTE";
export const SET_ACTIVE_NOTE_SELECTOR = "SET_ACTIVE_NOTE_SELECTOR";

export const ADD_CHORD = "ADD_CHORD";
export const REMOVE_CHORD = "REMOVE_CHORD";

export const ADD_SECTION = "ADD_SECTION";
export const REMOVE_SECTION = "REMOVE_SECTION";
export const SET_SECTION_NAME = "SET_SECTION_NAME";
export const SET_SECTION_TUNING = "SET_SECTION_TUNING";
export const ADD_SECTION_STRING = "ADD_SECTION_STRING";
export const REMOVE_SECTION_STRING = "REMOVE_SECTION_STRING";

export const SET_SHEET_NAME = "SET_SHEET_NAME";
export const SET_SHEET_STATE = "SET_SHEET_STATE";

// export const SELECT_MEASURE = 'SELECT_MEASURE';
// export const CLEAR_CHORD = 'CLEAR_CHORD';
// export const SET_CHORD_HOVERED = 'SET_CHORD_HOVERED';
